version: "3.6"
services:
  server:
    build:
      dockerfile: pod.Dockerfile
      context: ./serverv2
    image: server:v2
    ports:
      - 8080:8080
  curl:
    build:
      dockerfile: curl.Dockerfile
      context: ./curl
    image: curl
    depends_on:
      - server
